resources:
- name: concourse-examples
  type: git
  icon: bitbucket
  source:
    uri: https://github.com/karandit/examples

jobs:
- name: configure-self
  plan:
  - get: concourse-examples
    trigger: true
  - set_pipeline: reconfigure-pipelines
    file: concourse-examples/pipelines/reconfigure-pipelines.yml
- name: configure-pipelines
  public: true
  plan:
    - get: concourse-examples
      trigger: true
      passed: [configure-self]
    - set_pipeline: hello-world
      file: concourse-examples/pipelines/hello-world.yml
