resources:
- name: concourse-examples
  type: git
  icon: bitbucket
  source:
    uri: https://github.com/karandit/examples.git

jobs:
- name: configure-pipelines
  public: true
  plan:
    - get: concourse-examples
      trigger: true
    - set_pipeline: hello-world
      file: concourse-examples/pipelines/hello-world.yml
